### ISSUE TITLE
Front end switcher

### ISSUE THREAD

**Issue by dwainm** [mattyza/matty-theme-quickswitch#3]
Hey Matty, I've been using this plugin for a while now and I think the main use case here is for dev shops or theme developers.

Having the ability to switch theme's in the front end and have it reload the page is definitely a use case I can see many users benefiting from. 

If you think this is a valid use case I would like to give back to this plugin (it saves me a lot of clicks every day :: thanks ! - being able to change in the front end will save even more :P  )

**Comment by mattyza** [comment]
Go for it, Dwain! :)

There's a `redirect_to` parameter which you could use to redirect to the
current URL, btw. :)

**Comment by dwainm** [comment]
Thanks Matty :) 

```
todoList.push( this.issue );
```
